name: cover_page
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


# - - - - - - - - - - PACKAGES START - - - - - - - - - - #
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  url_launcher: ^6.2.6
  intl: ^0.19.0
  fluttertoast: ^8.2.5
  dropdown_button2: ^2.3.9
  share_plus: ^9.0.0


  # Animation
  circular_menu: ^3.0.0
  loading_animation_widget: ^1.2.1
  lottie: ^3.1.0
  page_transition: ^2.1.0
  animated_splash_screen: ^1.3.0


  # Pdf Packages
  pdf: ^3.10.8
  printing: ^5.12.0
  open_file: ^3.3.2
  path_provider: ^2.1.3


  # Icon Packages
  iconsax: ^0.0.8
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.6

  # Stage Management and Local Storage Package
  get: ^4.6.6
  get_storage: ^2.1.1


# - - - - - - - - - - PACKAGES END - - - - - - - - - - #

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2



flutter:
  uses-material-design: true

  # - - - - - - - - LOCAL ASSETS - - - - - - - - #
  assets:
    - assets/images/university_logo/
    - assets/logos/
    - assets/fonts/
    - assets/animations/


    # - - - - - - - - LOCAL FONTS - - - - - - - - #
  fonts:
      - family: Montserrat
        fonts:
            - asset: assets/fonts/open-sans.regular.ttf

      - family: Poppins
        fonts:
          - asset: assets/fonts/Poppins-Light.ttf
            weight: 300
          - asset: assets/fonts/Poppins-Regular.ttf
            weight: 400
          - asset: assets/fonts/Poppins-Medium.ttf
            weight: 500
          - asset: assets/fonts/Poppins-Italic.ttf
          - asset: assets/fonts/Poppins-MediumItalic.ttf
            weight: 500
          - asset: assets/fonts/Poppins-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Poppins-Bold.ttf
            weight: 800
  
  
